import { el, button, labeledField, setFeedback } from '../../ui/dom.js';
import { formatBRL } from '../../core/money.js';
import { COMPLEXITY_LEVELS } from './orcamento-calculator.js';
import { printCommercialQuote } from './pdf-service.js';
import { recordFromDraft } from './orcamento-model.js';

function input(type='text'){const n=el('input','mod-input');n.type=type;return n;}
function textarea(rows=3){const n=el('textarea','mod-input');n.rows=rows;return n;}
function select(){return el('select','mod-input');}
function option(value,label){const n=el('option','',label);n.value=String(value??'');return n;}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0;}
function today(){return new Date().toISOString().slice(0,10);}

export function renderOrcamentoView(root,{service,onChanged}){
  root.className='simple-module budget-module';
  let draft=service.createDraft();let currentRecord=null;let clients=[];

  const toolbar=el('div','module-toolbar');const titleWrap=el('div');titleWrap.append(el('h1','module-title','Orçamento'),el('p','module-subtitle','Motor modular, histórico compatível e PDF comercial sem dados internos.'));
  const tools=el('div','module-toolbar-actions');const search=input('search');search.classList.add('budget-search');search.placeholder='Buscar histórico…';const fresh=button('Novo','btn');const save=button('Salvar','btn btn-primary');const duplicate=button('Copiar','btn');const pdf=button('PDF comercial','btn');const whatsapp=button('WhatsApp','btn');tools.append(search,fresh,save,duplicate,pdf,whatsapp);toolbar.append(titleWrap,tools);
  const feedback=el('div','module-feedback');feedback.hidden=true;
  const body=el('div','module-body budget-body');const editor=el('div','budget-editor');const history=el('aside','module-card budget-history');body.append(editor,history);root.replaceChildren(toolbar,feedback,body);

  const clientSel=select();clientSel.append(option('','Cliente cadastrado (opcional)'));const clientName=input();const clientPhone=input();const vehicle=input();const plate=input();const year=input();const color=input();const km=input();const serviceText=textarea(3);const entry=input('date');const due=input('date');const priority=select();[['normal','Normal'],['urgente','Urgente'],['programado','Programado']].forEach(x=>priority.append(option(...x)));const payment=input();const warranty=input('number');warranty.min='0';
  const complexity=select();for(const level of COMPLEXITY_LEVELS)complexity.append(option(level.key,`${level.label} × ${level.multiplier.toFixed(1)}`));const hourRate=input('text');const margin=input('text');const discount=input('text');
  const publicNotes=textarea(3);const internalNotes=textarea(3);
  const freightDisplacement=input('text');const freightParts=input('text');const freightTow=input('text');

  const summary={labor:el('strong'),materials:el('strong'),parts:el('strong'),extras:el('strong'),base:el('strong'),margin:el('strong'),discount:el('strong'),total:el('strong','budget-total')};
  const scenario={m20:el('strong'),m30:el('strong'),m50:el('strong')};

  const laborList=el('div','budget-lines');const materialList=el('div','budget-lines');const serviceList=el('div','budget-lines');const partsList=el('div','budget-lines');const thirdList=el('div','budget-lines');

  function section(title){const card=el('section','module-card');card.append(el('h2','',title));return card;}
  const clientCard=section('Cliente e veículo');const cg=el('div','budget-grid');cg.append(labeledField('Cliente cadastrado',clientSel),labeledField('Nome do cliente',clientName),labeledField('Telefone',clientPhone),labeledField('Veículo',vehicle),labeledField('Placa',plate),labeledField('Ano',year),labeledField('Cor',color),labeledField('Km',km),labeledField('Entrada',entry),labeledField('Entrega prevista',due),labeledField('Prioridade',priority));clientCard.append(cg,labeledField('Serviço / escopo',serviceText));
  const laborCard=section('Mão de obra — cálculo interno');const lg=el('div','budget-grid budget-grid-compact');lg.append(labeledField('Complexidade',complexity),labeledField('R$ / hora',hourRate),labeledField('Margem %',margin),labeledField('Desconto %',discount));laborCard.append(lg,laborList);
  const materialsCard=section('Materiais internos');const addMaterial=button('＋ Material','btn btn-small');materialsCard.append(addMaterial,materialList);
  const servicesCard=section('Serviços / itens complementares');const serviceDiscount=input('text');const addService=button('＋ Item','btn btn-small');servicesCard.append(addService,serviceList,labeledField('Desconto fixo nesses itens',serviceDiscount));
  const partsCard=section('Peças Usadas & Recuperadas');const addPart=button('＋ Peça','btn btn-small');partsCard.append(addPart,partsList);
  const thirdCard=section('Terceiros e fretes');const addThird=button('＋ Terceiro','btn btn-small');const fg=el('div','budget-grid budget-grid-compact');fg.append(labeledField('Deslocamento',freightDisplacement),labeledField('Frete de peças',freightParts),labeledField('Reboque',freightTow));thirdCard.append(addThird,thirdList,fg);
  const condCard=section('Condições e observações');const condGrid=el('div','budget-grid');condGrid.append(labeledField('Pagamento',payment),labeledField('Garantia (dias)',warranty));condCard.append(condGrid,labeledField('Observações para o cliente',publicNotes),labeledField('Observações internas — não vão para o PDF',internalNotes));
  const summaryCard=section('Resumo interno');const sg=el('div','budget-summary');[['Mão de obra',summary.labor],['Materiais',summary.materials],['Peças / itens',summary.parts],['Terceiros + frete',summary.extras],['Base × complexidade',summary.base],['Margem embutida',summary.margin],['Desconto',summary.discount],['TOTAL',summary.total]].forEach(([label,value])=>{const box=el('div','budget-summary-box');box.append(el('span','',label),value);sg.append(box);});const scenarios=el('div','budget-scenarios');[['20%',scenario.m20],['30%',scenario.m30],['50%',scenario.m50]].forEach(([label,value])=>{const b=el('div');b.append(el('span','',`Cenário margem ${label}`),value);scenarios.append(b);});summaryCard.append(sg,scenarios);
  editor.append(clientCard,laborCard,materialsCard,servicesCard,partsCard,thirdCard,condCard,summaryCard);

  history.append(el('h2','','Histórico de orçamentos'));const historyList=el('div','budget-history-list');history.append(historyList);

  function textField(label,value,onChange,type='text'){const wrap=el('label','budget-line-field');wrap.append(el('span','mod-label',label));const ctl=input(type);ctl.value=value??'';ctl.addEventListener('input',()=>onChange(ctl.value));wrap.append(ctl);return ctl;}
  function removeButton(onClick){const b=button('✕','btn btn-small btn-danger');b.addEventListener('click',onClick);return b;}

  function renderLabor(){laborList.replaceChildren();draft.laborProcesses.forEach((row,index)=>{const line=el('div','budget-line budget-labor-line');line.append(el('strong','',row.label||row.key));textField('Horas',row.hours,v=>{draft.laborProcesses[index].hours=v;recalc();},'text');laborList.append(line);});}
  function renderMaterials(){materialList.replaceChildren();if(!draft.materials.length)materialList.append(el('p','empty-state','Nenhum material interno lançado.'));draft.materials.forEach((row,index)=>{const line=el('div','budget-line');textField('Material',row.name,v=>draft.materials[index].name=v);textField('Qtd.',row.qty,v=>{draft.materials[index].qty=v;recalc();});textField('Custo un.',row.unit,v=>{draft.materials[index].unit=v;recalc();});line.append(removeButton(()=>{draft.materials.splice(index,1);renderMaterials();recalc();}));materialList.append(line);});}
  function renderServices(){serviceList.replaceChildren();if(!draft.serviceItems.length)serviceList.append(el('p','empty-state','Nenhum item complementar.'));draft.serviceItems.forEach((row,index)=>{const line=el('div','budget-line');textField('Descrição',row.desc,v=>draft.serviceItems[index].desc=v);textField('Qtd.',row.qty,v=>{draft.serviceItems[index].qty=v;recalc();});textField('Valor un.',row.value,v=>{draft.serviceItems[index].value=v;recalc();});line.append(removeButton(()=>{draft.serviceItems.splice(index,1);renderServices();recalc();}));serviceList.append(line);});}
  function renderParts(){partsList.replaceChildren();if(!draft.parts.length)partsList.append(el('p','empty-state','Nenhuma peça usada ou recuperada.'));draft.parts.forEach((row,index)=>{const line=el('div','budget-line');textField('Peça',row.name,v=>draft.parts[index].name=v);textField('Condição',row.condition,v=>draft.parts[index].condition=v);textField('Valor',row.value,v=>{draft.parts[index].value=v;recalc();});line.append(removeButton(()=>{draft.parts.splice(index,1);renderParts();recalc();}));partsList.append(line);});}
  function renderThird(){thirdList.replaceChildren();if(!draft.thirdParties.length)thirdList.append(el('p','empty-state','Nenhum terceiro lançado.'));draft.thirdParties.forEach((row,index)=>{const line=el('div','budget-line');textField('Terceiro / serviço',row.desc,v=>draft.thirdParties[index].desc=v);textField('Valor',row.value,v=>{draft.thirdParties[index].value=v;recalc();});line.append(removeButton(()=>{draft.thirdParties.splice(index,1);renderThird();recalc();}));thirdList.append(line);});}

  function pushFieldsToDraft(){draft.clientId=clientSel.value||null;draft.clientName=clientName.value;draft.clientPhone=clientPhone.value;draft.vehicle=vehicle.value;draft.vehiclePlate=plate.value;draft.vehicleYear=year.value;draft.vehicleColor=color.value;draft.vehicleKm=km.value;draft.service=serviceText.value;draft.entryDate=entry.value;draft.dueDate=due.value;draft.priority=priority.value;draft.payment=payment.value;draft.warrantyDays=warranty.value;draft.complexity=complexity.value;draft.hourRate=hourRate.value;draft.marginPercent=margin.value;draft.discountPercent=discount.value;draft.serviceItemsDiscount=serviceDiscount.value;draft.freight={displacement:freightDisplacement.value,parts:freightParts.value,tow:freightTow.value};draft.notes=publicNotes.value;draft.internalNotes=internalNotes.value;}
  function recalc(){pushFieldsToDraft();const c=service.calculate(draft);summary.labor.textContent=formatBRL(c.labor);summary.materials.textContent=formatBRL(c.materials);summary.parts.textContent=formatBRL(c.serviceItemsNet+c.recoveredParts);summary.extras.textContent=formatBRL(c.extras);summary.base.textContent=formatBRL(c.base);summary.margin.textContent=formatBRL(c.withMargin-c.base);summary.discount.textContent=`− ${formatBRL(c.discountAmount)}`;summary.total.textContent=formatBRL(c.final);scenario.m20.textContent=formatBRL(c.scenarios.margin20);scenario.m30.textContent=formatBRL(c.scenarios.margin30);scenario.m50.textContent=formatBRL(c.scenarios.margin50);}

  function fill(d){draft=structuredClone(d);clientSel.value=draft.clientId==null?'':String(draft.clientId);clientName.value=draft.clientName||'';clientPhone.value=draft.clientPhone||'';vehicle.value=draft.vehicle||'';plate.value=draft.vehiclePlate||'';year.value=draft.vehicleYear||'';color.value=draft.vehicleColor||'';km.value=draft.vehicleKm||'';serviceText.value=draft.service||'';entry.value=draft.entryDate||today();due.value=draft.dueDate||'';priority.value=draft.priority||'normal';payment.value=draft.payment||'';warranty.value=draft.warrantyDays||'';complexity.value=draft.complexity||'basico';hourRate.value=draft.hourRate||'';margin.value=draft.marginPercent||'';discount.value=draft.discountPercent||'';serviceDiscount.value=draft.serviceItemsDiscount||'';freightDisplacement.value=draft.freight?.displacement||'';freightParts.value=draft.freight?.parts||'';freightTow.value=draft.freight?.tow||'';publicNotes.value=draft.notes||'';internalNotes.value=draft.internalNotes||'';renderLabor();renderMaterials();renderServices();renderParts();renderThird();recalc();}

  function historyCard(record){const wrap=el('article',`budget-history-row${currentRecord?.id===record.id?' active':''}`);const info=el('button','budget-history-open');info.type='button';info.append(el('strong','',record.cliente??record.clientName??'Cliente'),el('span','',record.veiculo??record.vehicle??'Veículo'),el('span','',record.servico??record.service??record.descricao??'Serviço'),el('span','muted-small',`${record.data??record.entryDate??'—'} · ${record.status??'Salvo'}`));const amount=el('strong','',formatBRL(record.total));wrap.append(info,amount);info.addEventListener('click',async()=>{const loaded=await service.get(record.id);if(!loaded)return;currentRecord=loaded.record;fill(loaded.draft);await renderHistory();});return wrap;}
  async function renderHistory(){const rows=await service.list({query:search.value});historyList.replaceChildren();if(!rows.length){historyList.append(el('p','empty-state','Nenhum orçamento salvo.'));return;}for(const row of rows)historyList.append(historyCard(row));}
  async function loadClients(){clients=await service.clients();const prev=clientSel.value;clientSel.replaceChildren(option('','Cliente cadastrado (opcional)'));for(const c of clients.sort((a,b)=>String(a.name??a.nome??'').localeCompare(String(b.name??b.nome??''),'pt-BR')))clientSel.append(option(c.id,c.name??c.nome??`Cliente ${c.id}`));if([...clientSel.options].some(o=>o.value===prev))clientSel.value=prev;}

  const updateInputs=[clientName,clientPhone,vehicle,plate,year,color,km,serviceText,entry,due,priority,payment,warranty,complexity,hourRate,margin,discount,serviceDiscount,freightDisplacement,freightParts,freightTow,publicNotes,internalNotes];for(const ctl of updateInputs)ctl.addEventListener(ctl.tagName==='SELECT'?'change':'input',recalc);
  clientSel.addEventListener('change',()=>{const c=clients.find(x=>String(x.id)===clientSel.value);if(c){clientName.value=c.name??c.nome??'';clientPhone.value=c.fone??c.phone??'';const v=(c.veiculos||[])[0];if(v){vehicle.value=v.marca??v.name??'';plate.value=v.placa??'';year.value=v.ano??'';color.value=v.cor??'';}}recalc();});
  addMaterial.addEventListener('click',()=>{draft.materials.push({name:'',qty:1,unit:0,unid:'Un'});renderMaterials();recalc();});addService.addEventListener('click',()=>{draft.serviceItems.push({desc:'',qty:1,value:0});renderServices();recalc();});addPart.addEventListener('click',()=>{draft.parts.push({name:'',condition:'Boa',value:0,qty:1});renderParts();recalc();});addThird.addEventListener('click',()=>{draft.thirdParties.push({desc:'',value:0});renderThird();recalc();});
  fresh.addEventListener('click',()=>{currentRecord=null;fill(service.createDraft());setFeedback(feedback,'Novo orçamento iniciado sem dados fictícios.','ok');renderHistory();});
  save.addEventListener('click',async()=>{try{pushFieldsToDraft();const record=await service.save(draft);currentRecord=record;draft.id=record.id;setFeedback(feedback,'Orçamento salvo no histórico modular.','ok');await renderHistory();onChanged?.();}catch(e){setFeedback(feedback,e.message,'error');}});
  duplicate.addEventListener('click',async()=>{if(!currentRecord){setFeedback(feedback,'Salve o orçamento antes de copiar.','error');return;}try{const record=await service.duplicate(currentRecord.id);const loaded=await service.get(record.id);currentRecord=loaded.record;fill(loaded.draft);setFeedback(feedback,'Cópia criada com novo ID.','ok');await renderHistory();onChanged?.();}catch(e){setFeedback(feedback,e.message,'error');}});
  pdf.addEventListener('click',async()=>{try{pushFieldsToDraft();const preview=recordFromDraft(draft,currentRecord);const cfg=await service.configuration();printCommercialQuote(preview,cfg);setFeedback(feedback,'Documento comercial preparado para impressão/PDF. Use Salvar para gravar alterações.','ok');}catch(e){setFeedback(feedback,e.message,'error');}});
  whatsapp.addEventListener('click',async()=>{try{if(!currentRecord){pushFieldsToDraft();currentRecord=await service.save(draft);draft.id=currentRecord.id;}const model=await service.commercialModel(currentRecord);const phone=String(model.clientPhone||'').replace(/\D/g,'');const normalized=phone&&phone.length<=11?`55${phone}`:phone;const msg=`Olá, ${model.clientName||'cliente'}! Segue o orçamento ${model.quoteNumber||''} para ${model.vehicle||'seu veículo'}. Serviço: ${model.service||'serviço'}. Total: ${formatBRL(model.total)}.${model.payment?` Pagamento: ${model.payment}.`:''}`;const url=normalized?`https://wa.me/${normalized}?text=${encodeURIComponent(msg)}`:`https://web.whatsapp.com/send?text=${encodeURIComponent(msg)}`;window.open(url,'_blank','noopener,noreferrer');}catch(e){setFeedback(feedback,e.message,'error');}});
  search.addEventListener('input',renderHistory);

  async function refresh(){await loadClients();if(!draft.entryDate)draft.entryDate=today();fill(draft);await renderHistory();}
  refresh();return {refresh};
}
