import { formatBRL } from '../../core/money.js';
import { el, button, labeledField, setFeedback } from '../../ui/dom.js';

function input(type='text'){const x=el('input','mod-input');x.type=type;return x;}
function metric(label){const card=el('article','module-metric');const value=el('strong','module-metric-value','0');card.append(el('span','module-metric-label',label),value);return{card,value};}

export function renderMetasView(root,{service,categoriesService,onChanged=()=>{}}){
  root.replaceChildren(); let editingId=null;
  const page=el('section','simple-module');const head=el('div','module-toolbar');const title=el('div');title.append(el('h1','module-title','Metas'),el('p','module-subtitle','O realizado é recalculado a partir das receitas reais do mês corrente.'));head.append(title);const feedback=el('div','module-feedback');feedback.hidden=true;const body=el('div','module-body');
  const principal=el('section','module-card');principal.append(el('h2','','Meta mensal de faturamento'));const principalForm=el('form','module-form-row');const principalInput=input('number');principalInput.min='0';principalInput.step='100';const principalSave=button('Salvar meta','btn btn-primary','submit');principalForm.append(labeledField('Valor mensal',principalInput),principalSave);principal.append(principalForm);
  const metrics=el('div','module-metrics');const mMeta=metric('Meta');const mReal=metric('Realizado');const mMissing=metric('Falta');const mProjection=metric('Projeção');metrics.append(mMeta.card,mReal.card,mMissing.card,mProjection.card);
  const pace=el('section','module-card');const paceText=el('p','status-line');pace.append(el('h2','','Ritmo do mês'),paceText);
  const goalCard=el('section','module-card');const goalHead=el('div','module-card-head');goalHead.append(el('h2','','Metas por categoria'));const goalForm=el('form','module-form-row');const category=el('select','mod-input');const value=input('number');value.min='0';value.step='100';const save=button('Salvar categoria','btn btn-primary','submit');const cancel=button('Cancelar edição','btn');cancel.hidden=true;goalForm.append(labeledField('Categoria',category),labeledField('Meta mensal',value),save,cancel);const list=el('div','goal-list');goalCard.append(goalHead,goalForm,list);body.append(principal,metrics,pace,goalCard);page.append(head,feedback,body);root.append(page);
  async function fillCategories(selected=''){const rows=await categoriesService.list();category.replaceChildren();for(const row of rows){const o=el('option','',row.name);o.value=row.name;o.selected=row.name===selected;category.append(o);}if(selected&&!rows.some(r=>r.name===selected)){const o=el('option','',selected);o.value=selected;o.selected=true;category.append(o);}}
  function resetEditor(){editingId=null;save.textContent='Salvar categoria';cancel.hidden=true;value.value='';}
  async function changed(message){setFeedback(feedback,message,'ok');resetEditor();await refresh();await onChanged();}
  async function refresh(){const summary=await service.summary();principalInput.value=summary.meta||'';mMeta.value.textContent=formatBRL(summary.meta);mReal.value.textContent=formatBRL(summary.real);mMissing.value.textContent=formatBRL(summary.missing);mProjection.value.textContent=formatBRL(summary.projection);paceText.textContent=`${summary.pct}% da meta · média ${formatBRL(summary.dailyAverage)}/dia · necessidade ${formatBRL(summary.neededPerDay)}/dia nos ${summary.remainingDays} dia(s) restantes.`;await fillCategories();list.replaceChildren();if(!summary.categories.length){list.append(el('p','empty-state','Nenhuma meta por categoria cadastrada.'));return;}for(const row of summary.categories){const card=el('article','goal-row');const info=el('div','goal-info');const pct=row.meta>0?Math.min(Math.round(row.real/row.meta*100),100):0;info.append(el('strong','',row.category),el('span','muted-small',`Realizado ${formatBRL(row.real)} · Meta ${formatBRL(row.meta)} · ${pct}%`));const bar=el('div','progress-track');const fill=el('span','progress-fill');fill.style.width=`${pct}%`;bar.append(fill);info.append(bar);const actions=el('div','row-actions');const edit=button('Editar','btn btn-small');const del=button('Excluir','btn btn-small btn-danger');edit.addEventListener('click',async()=>{editingId=row.id;await fillCategories(row.category);value.value=row.meta;save.textContent='Salvar alterações';cancel.hidden=false;goalCard.scrollIntoView({behavior:'smooth',block:'start'});});del.addEventListener('click',async()=>{if(!window.confirm(`Remover a meta de "${row.category}"?`))return;try{await service.remove(row.id);await changed('Meta removida.');}catch(e){setFeedback(feedback,e.message,'error');}});actions.append(edit,del);card.append(info,actions);list.append(card);}}
  principalForm.addEventListener('submit',async e=>{e.preventDefault();try{await service.setPrincipal(principalInput.value);await changed('Meta principal atualizada.');}catch(err){setFeedback(feedback,err.message,'error');}});
  goalForm.addEventListener('submit',async e=>{e.preventDefault();try{if(editingId==null)await service.upsertCategoryGoal(category.value,value.value);else await service.renameCategoryGoal(editingId,category.value,value.value);await changed('Meta por categoria salva.');}catch(err){setFeedback(feedback,err.message,'error');}});cancel.addEventListener('click',resetEditor);refresh();return{refresh};
}
