import { el, button, labeledField, setFeedback } from '../../ui/dom.js';

function input(type='text'){const n=el('input','mod-input');n.type=type;return n;}
function message(role,text,source=''){const row=el('article',`consultor-message ${role}`);const avatar=el('div','consultor-avatar',role==='user'?'Você':'IA');const bubble=el('div','consultor-bubble');const copy=el('div','consultor-copy');for(const part of String(text||'').split(/\n\n+/)){if(!part)continue;copy.append(el('p','',part));}bubble.append(copy);if(source)bubble.append(el('span','consultor-source',source==='gateway'?'Gateway externo':'Orientação local por regras'));row.append(avatar,bubble);return row;}

export function renderConsultorView(root,{service}){
  root.className='simple-module consultor-module';let context='geral';const toolbar=el('div','module-toolbar');const title=el('div');title.append(el('h1','module-title','Consultor IA'),el('p','module-subtitle','Assistência técnica e gerencial em modo somente leitura. O modo local usa regras predefinidas. O envio externo é opcional e inclui a pergunta e indicadores financeiros agregados.'));toolbar.append(title);const feedback=el('div','module-feedback');feedback.hidden=true;const layout=el('div','consultor-layout');root.replaceChildren(toolbar,feedback,layout);

  const sidebar=el('aside','consultor-sidebar');sidebar.append(el('strong','consultor-sidebar-title','Contextos'));const contextButtons=new Map();for(const [id,cfg] of Object.entries(service.contexts)){const b=button(cfg.label,`consultor-context${id==='geral'?' active':''}`);b.title=cfg.description;b.addEventListener('click',()=>{context=id;for(const [k,x] of contextButtons)x.classList.toggle('active',k===id);question.placeholder=`Contexto: ${cfg.label} — digite sua pergunta…`;});contextButtons.set(id,b);sidebar.append(b);}const chips=el('div','consultor-chips');chips.append(el('strong','consultor-sidebar-title','Atalhos'));for(const text of ['Como está meu faturamento e margem?','Como devo precificar este serviço?','Checklist antes da entrega','Quais serviços aparecem mais no histórico?']){const b=button(text,'consultor-chip');b.addEventListener('click',()=>{question.value=text;question.focus();});chips.append(b);}sidebar.append(chips);

  const main=el('section','consultor-main');const chat=el('div','consultor-chat');const welcome=el('div','consultor-welcome');welcome.append(el('h2','','Consultor OficinaOS'),el('p','','O modo local usa orientações predefinidas e indicadores do próprio sistema. IA externa depende de um servidor configurado. Nenhuma resposta altera cadastros, finanças ou OS.'));chat.append(welcome);
  const composer=el('form','consultor-composer');const question=el('textarea','mod-input consultor-input');question.rows=3;question.placeholder='Contexto: Consulta Livre — digite sua pergunta…';const send=button('Enviar','btn btn-primary','submit');const preferExternal=input('checkbox');const externalLabel=el('label','consultor-external-toggle');externalLabel.append(preferExternal,el('span','','Enviar pergunta e indicadores financeiros ao gateway configurado'));composer.append(question,externalLabel,send);main.append(chat,composer);

  const gateway=el('aside','consultor-gateway');gateway.append(el('h2','','Integração externa segura'),el('p','module-subtitle','O frontend não armazena chave de API. Configure um endpoint HTTPS que mantenha os segredos no servidor.'));const endpoint=input('url');endpoint.placeholder='https://seu-servidor/api/oficinaos-ai';const timeout=input('number');timeout.min='2000';timeout.max='60000';const enabled=input('checkbox');const save=button('Salvar gateway','btn');const gatewayStatus=el('p','muted-small');gateway.append(labeledField('Endpoint',endpoint),labeledField('Timeout (ms)',timeout));const enLabel=el('label','consultor-external-toggle');enLabel.append(enabled,el('span','','Ativar gateway'));gateway.append(enLabel,save,gatewayStatus);layout.append(sidebar,main,gateway);

  async function loadConfig(){const cfg=await service.getGatewayConfig();endpoint.value=cfg.endpoint||'';timeout.value=cfg.timeoutMs||15000;enabled.checked=cfg.enabled===true;preferExternal.disabled=!cfg.enabled;gatewayStatus.textContent=cfg.enabled?'Gateway ativo. O envio inclui sua pergunta e indicadores financeiros; nomes de clientes, serviços e categorias não são incluídos automaticamente.':'Modo local ativo; gateway externo desativado.';}
  async function submit(){const text=question.value.trim();if(!text)return;question.value='';chat.append(message('user',text));chat.scrollTop=chat.scrollHeight;send.disabled=true;send.textContent='Consultando…';try{const result=await service.ask({message:text,context,preferExternal:preferExternal.checked});chat.append(message('assistant',result.answer,result.source));if(result.externalError)setFeedback(feedback,`Gateway indisponível; resposta local usada. ${result.externalError}`,'error');else setFeedback(feedback,'','ok');}catch(e){setFeedback(feedback,e.message,'error');}finally{send.disabled=false;send.textContent='Enviar';chat.scrollTop=chat.scrollHeight;}}
  composer.addEventListener('submit',e=>{e.preventDefault();submit();});question.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}});save.addEventListener('click',async()=>{try{const cfg=await service.configureGateway({endpoint:endpoint.value,timeoutMs:Number(timeout.value),enabled:enabled.checked});setFeedback(feedback,'Configuração do gateway salva.','ok');preferExternal.disabled=!cfg.enabled;await loadConfig();}catch(e){setFeedback(feedback,e.message,'error');}});
  loadConfig();return{refresh:loadConfig};
}
