import { el, button, labeledField, setFeedback } from '../../ui/dom.js';
import { formatBRL } from '../../core/money.js';

function input(type='text'){const n=el('input','mod-input');n.type=type;return n;}
function pct(v){return `${Number(v||0).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;}
function metric(label,value,cls=''){const c=el('article',`report-metric ${cls}`);c.append(el('span','report-metric-label',label),el('strong','report-metric-value',value));return c;}
function section(title,subtitle=''){const c=el('section','card report-card');c.append(el('h2','',title));if(subtitle)c.append(el('p','module-subtitle',subtitle));return c;}
function empty(text){return el('p','empty-state',text);}

function renderMonthlyChart(host,rows){host.replaceChildren();if(!rows.length){host.append(empty('Sem lançamentos suficientes para o gráfico.'));return;}const max=Math.max(1,...rows.flatMap(r=>[r.receitas,r.despesas]));const chart=el('div','report-month-chart');for(const row of rows){const col=el('div','report-month-col');const bars=el('div','report-month-bars');const rec=el('div','report-bar report-bar-rec');rec.style.height=`${Math.max(2,row.receitas/max*140)}px`;rec.title=`Receitas ${formatBRL(row.receitas)}`;const dep=el('div','report-bar report-bar-dep');dep.style.height=`${Math.max(2,row.despesas/max*140)}px`;dep.title=`Despesas ${formatBRL(row.despesas)}`;bars.append(rec,dep);col.append(bars,el('span','report-axis-label',row.label));chart.append(col);}host.append(chart);}
function renderMarginChart(host,rows){host.replaceChildren();if(!rows.length){host.append(empty('Sem dados de margem.'));return;}const chart=el('div','report-margin-chart');for(const row of rows){const col=el('div','report-margin-col');const tag=el('span',`report-margin-tag ${row.margem>=20?'good':row.margem>0?'mid':'bad'}`,`${row.margem.toFixed(0)}%`);const bar=el('div',`report-margin-bar ${row.margem>=20?'good':row.margem>0?'mid':'bad'}`);bar.style.height=`${Math.max(2,Math.min(110,Math.abs(row.margem)/60*110))}px`;col.append(tag,bar,el('span','report-axis-label',row.label));chart.append(col);}host.append(chart);}
function renderRanking(host,rows){host.replaceChildren();if(!rows.length){host.append(empty('Sem dados suficientes para ranking.'));return;}const max=rows[0]?.value||1;rows.forEach((row,i)=>{const r=el('div','report-rank-row');r.append(el('span','report-rank-pos',String(i+1)),el('span','report-rank-name',row.name));const track=el('div','report-rank-track'),fill=el('div','report-rank-fill');fill.style.width=`${Math.max(1,row.value/max*100)}%`;track.append(fill);r.append(track,el('strong','report-rank-value',formatBRL(row.value)));host.append(r);});}
function renderSeasonal(host,rows){host.replaceChildren();const max=Math.max(1,...rows.map(x=>x.receitas));const chart=el('div','report-seasonal-chart');for(const row of rows){const col=el('div','report-seasonal-col');const bar=el('div','report-seasonal-bar');bar.style.height=`${Math.max(2,row.receitas/max*100)}px`;bar.title=`${row.label}: ${formatBRL(row.receitas)} · ${row.count} receita(s)`;col.append(bar,el('span','report-axis-label',row.label));chart.append(col);}host.append(chart);}
function renderAnnual(host,rows){host.replaceChildren();if(!rows.length){host.append(empty('Nenhum ano com lançamentos.'));return;}for(const row of rows){const r=el('div','report-annual-row');const y=el('strong','report-year',row.year);const vals=el('div','report-annual-values');vals.append(el('span','positive',formatBRL(row.receitas)),el('span','negative',`−${formatBRL(row.despesas)}`));r.append(y,vals,el('span',`report-margin-tag ${row.margem>=15?'good':row.margem>0?'mid':'bad'}`,pct(row.margem)));host.append(r);}}
function renderLimits(host,rows){host.replaceChildren();if(!rows.length){host.append(empty('Nenhum limite de categoria configurado.'));return;}for(const row of rows){const wrap=el('div','report-limit-row');const line=el('div','report-limit-head');line.append(el('strong','',row.category),el('span',row.over?'negative':'muted',`${formatBRL(row.spent)} / ${formatBRL(row.limit)}${row.over?' · ACIMA':''}`));const track=el('div','report-limit-track'),fill=el('div',`report-limit-fill${row.over?' over':row.pct>80?' warn':''}`);fill.style.width=`${Math.min(100,row.pct)}%`;track.append(fill);wrap.append(line,track);host.append(wrap);}}

export function renderRelatoriosView(root,{service,onChanged}){
  root.className='simple-module reports-module';const toolbar=el('div','module-toolbar');const title=el('div');title.append(el('h1','module-title','Relatórios'),el('p','module-subtitle','Indicadores dos lançamentos cadastrados, incluindo pendentes. Metas usam apenas receitas recebidas.'));const tools=el('div','module-toolbar-actions');const refreshBtn=button('Atualizar','btn btn-primary');tools.append(refreshBtn);toolbar.append(title,tools);const feedback=el('div','module-feedback');feedback.hidden=true;const body=el('div','module-body reports-body');root.replaceChildren(toolbar,feedback,body);

  const currentCard=section('Resumo do mês');const metrics=el('div','report-metrics');currentCard.append(metrics);const period=el('p','report-period');currentCard.append(period);
  const chartCard=section('Receitas × Despesas','Últimos 12 meses. Transferências são excluídas do resultado.');const monthlyHost=el('div');chartCard.append(monthlyHost);
  const marginCard=section('Margem mensal');const marginHost=el('div');marginCard.append(marginHost);
  const clientsCard=section('Ranking de clientes','Receitas vinculadas ao cliente; quando o vínculo legado não existe, usa a descrição do lançamento.');const clientsHost=el('div','report-ranking');clientsCard.append(clientsHost);
  const servicesCard=section('Ranking de serviços/categorias');const servicesHost=el('div','report-ranking');servicesCard.append(servicesHost);
  const seasonalCard=section('Sazonalidade histórica','Receita acumulada por mês do ano em todos os anos carregados.');const seasonalHost=el('div');seasonalCard.append(seasonalHost);
  const annualCard=section('Resumo anual');const annualHost=el('div');annualCard.append(annualHost);
  const goalCard=section('Metas');const goalHost=el('div');goalCard.append(goalHost);
  const limitsCard=section('Limites por categoria','Compatível com fp_limites do Clean v8.');const limitsHost=el('div');const limitsTools=el('div','report-limit-editor');const addCategory=input();addCategory.placeholder='Categoria';const addValue=input('number');addValue.min='0';addValue.step='0.01';addValue.placeholder='Limite R$';const addBtn=button('Adicionar/atualizar limite','btn');limitsTools.append(labeledField('Categoria',addCategory),labeledField('Limite',addValue),addBtn);limitsCard.append(limitsHost,limitsTools);
  const grid=el('div','reports-grid');grid.append(chartCard,marginCard,clientsCard,servicesCard,seasonalCard,annualCard,goalCard,limitsCard);body.append(currentCard,grid);

  let lastLimits={};
  async function render(){try{const data=await service.dashboard();period.textContent=data.period;metrics.replaceChildren(metric('Receitas',formatBRL(data.current.receitas),'positive'),metric('Despesas',formatBRL(data.current.despesas),'negative'),metric('Resultado',formatBRL(data.current.lucro),data.current.lucro>=0?'positive':'negative'),metric('Margem',pct(data.current.margem)),metric('Orçamentos',data.current.budgets),metric('OS entregues',data.current.delivered));renderMonthlyChart(monthlyHost,data.series);renderMarginChart(marginHost,data.series);renderRanking(clientsHost,data.clients);renderRanking(servicesHost,data.services);renderSeasonal(seasonalHost,data.seasonal);renderAnnual(annualHost,data.annual);goalHost.replaceChildren();if(data.goals?.meta>0){const g=el('div','report-goal');g.append(metric('Meta',formatBRL(data.goals.meta)),metric('Realizado',formatBRL(data.goals.real)),metric('Progresso',`${Math.round(data.goals.pct||0)}%`),metric('Projeção',formatBRL(data.goals.projection)),metric('Falta',formatBRL(data.goals.missing)));goalHost.append(g);}else goalHost.append(empty('Nenhuma meta principal configurada.'));renderLimits(limitsHost,data.limits);lastLimits=Object.fromEntries(data.limits.map(x=>[x.category,x.limit]));}catch(e){setFeedback(feedback,e.message,'error');}}
  refreshBtn.addEventListener('click',render);addBtn.addEventListener('click',async()=>{try{const category=addCategory.value.trim(),value=Number(String(addValue.value).replace(',','.'));if(!category||!Number.isFinite(value)||value<=0)throw new Error('Informe categoria e limite maior que zero.');lastLimits[category]=value;await service.updateLimits(lastLimits);addCategory.value='';addValue.value='';setFeedback(feedback,'Limite atualizado.','ok');onChanged?.();await render();}catch(e){setFeedback(feedback,e.message,'error');}});
  render();return{refresh:render};
}
