// Lista padrão preservada da baseline Clean v8. Só é carregada por ação explícita do usuário.
export const ESTOQUE_DEFAULT = Object.freeze([
  {id:101,nome:'Massa Poliéster (3,6kg)',name:'Massa Poliéster (3,6kg)',cat:'funil',unid:'Kg',qty:0,custo:85.0,unit:85.0,minimo:1,minQty:1,forn:''},
  {id:102,nome:'Massa Plástica / Massa Rápida',name:'Massa Plástica / Massa Rápida',cat:'funil',unid:'Kg',qty:0,custo:40.0,unit:40.0,minimo:1,minQty:1,forn:''},
  {id:103,nome:'Massa UV',name:'Massa UV',cat:'funil',unid:'Un',qty:0,custo:55.0,unit:55.0,minimo:1,minQty:1,forn:''},
  {id:104,nome:'Removedor de Ferrugem',name:'Removedor de Ferrugem',cat:'funil',unid:'L',qty:0,custo:28.0,unit:28.0,minimo:1,minQty:1,forn:''},
  {id:105,nome:'Desengraxante / Anti-Silicone',name:'Desengraxante / Anti-Silicone',cat:'funil',unid:'L',qty:0,custo:22.0,unit:22.0,minimo:1,minQty:1,forn:''},
  {id:106,nome:'Adesivo Plástico Alta Aderência',name:'Adesivo Plástico Alta Aderência',cat:'funil',unid:'Un',qty:0,custo:35.0,unit:35.0,minimo:1,minQty:1,forn:''},
  {id:107,nome:'Massa Protetora Assoalho',name:'Massa Protetora Assoalho',cat:'funil',unid:'Kg',qty:0,custo:30.0,unit:30.0,minimo:1,minQty:1,forn:''},
  {id:108,nome:'Lixa a Seco 80',name:'Lixa a Seco 80',cat:'funil',unid:'Un',qty:0,custo:2.5,unit:2.5,minimo:5,minQty:5,forn:''},
  {id:109,nome:'Lixa a Seco 120',name:'Lixa a Seco 120',cat:'funil',unid:'Un',qty:0,custo:2.5,unit:2.5,minimo:5,minQty:5,forn:''},
  {id:110,nome:'Lixa a Seco 180',name:'Lixa a Seco 180',cat:'funil',unid:'Un',qty:0,custo:2.5,unit:2.5,minimo:5,minQty:5,forn:''},
  {id:111,nome:'Lixa a Seco 220',name:'Lixa a Seco 220',cat:'funil',unid:'Un',qty:0,custo:3.0,unit:3.0,minimo:5,minQty:5,forn:''},
  {id:112,nome:'Eletrodo / Fio MIG 0.8mm (5kg)',name:'Eletrodo / Fio MIG 0.8mm (5kg)',cat:'solda',unid:'Bobina',qty:0,custo:120.0,unit:120.0,minimo:1,minQty:1,forn:''},
  {id:113,nome:'Gás Argônio / CO₂ (mistura)',name:'Gás Argônio / CO₂ (mistura)',cat:'solda',unid:'Un',qty:0,custo:180.0,unit:180.0,minimo:1,minQty:1,forn:''},
  {id:114,nome:'Varão Oxiacetilênico',name:'Varão Oxiacetilênico',cat:'solda',unid:'Un',qty:0,custo:45.0,unit:45.0,minimo:1,minQty:1,forn:''},
  {id:115,nome:'Primer Universal',name:'Primer Universal',cat:'prep',unid:'L',qty:0,custo:60.0,unit:60.0,minimo:1,minQty:1,forn:''},
  {id:116,nome:'Primer PU',name:'Primer PU',cat:'prep',unid:'L',qty:0,custo:85.0,unit:85.0,minimo:1,minQty:1,forn:''},
  {id:117,nome:'Primer UV',name:'Primer UV',cat:'prep',unid:'L',qty:0,custo:95.0,unit:95.0,minimo:1,minQty:1,forn:''},
  {id:118,nome:'Lixa a Seco 320',name:'Lixa a Seco 320',cat:'prep',unid:'Un',qty:0,custo:3.0,unit:3.0,minimo:5,minQty:5,forn:''},
  {id:119,nome:'Lixa a Seco 400',name:'Lixa a Seco 400',cat:'prep',unid:'Un',qty:0,custo:3.5,unit:3.5,minimo:5,minQty:5,forn:''},
  {id:120,nome:'Lixa a Seco 600',name:'Lixa a Seco 600',cat:'prep',unid:'Un',qty:0,custo:4.0,unit:4.0,minimo:5,minQty:5,forn:''},
  {id:121,nome:'Lixa D\'água 320',name:'Lixa D\'água 320',cat:'prep',unid:'Un',qty:0,custo:3.5,unit:3.5,minimo:5,minQty:5,forn:''},
  {id:122,nome:'Lixa D\'água 600',name:'Lixa D\'água 600',cat:'prep',unid:'Un',qty:0,custo:3.5,unit:3.5,minimo:5,minQty:5,forn:''},
  {id:123,nome:'Lixa D\'água 800',name:'Lixa D\'água 800',cat:'prep',unid:'Un',qty:0,custo:4.0,unit:4.0,minimo:5,minQty:5,forn:''},
  {id:124,nome:'Lixa D\'água 1200',name:'Lixa D\'água 1200',cat:'prep',unid:'Un',qty:0,custo:4.5,unit:4.5,minimo:5,minQty:5,forn:''},
  {id:125,nome:'Lixa D\'água 1500',name:'Lixa D\'água 1500',cat:'prep',unid:'Un',qty:0,custo:5.0,unit:5.0,minimo:5,minQty:5,forn:''},
  {id:126,nome:'Lixa D\'água 2000',name:'Lixa D\'água 2000',cat:'prep',unid:'Un',qty:0,custo:5.0,unit:5.0,minimo:5,minQty:5,forn:''},
  {id:127,nome:'Lixa D\'água 3000',name:'Lixa D\'água 3000',cat:'prep',unid:'Un',qty:0,custo:5.5,unit:5.5,minimo:5,minQty:5,forn:''},
  {id:128,nome:'Disco de Lixa Roto-orbital',name:'Disco de Lixa Roto-orbital',cat:'prep',unid:'Un',qty:0,custo:8.0,unit:8.0,minimo:5,minQty:5,forn:''},
  {id:129,nome:'Removedor Pastoso Tinta/Verniz',name:'Removedor Pastoso Tinta/Verniz',cat:'prep',unid:'L',qty:0,custo:45.0,unit:45.0,minimo:1,minQty:1,forn:''},
  {id:130,nome:'Fita Crepe Automotiva 18mm',name:'Fita Crepe Automotiva 18mm',cat:'masc',unid:'Un',qty:0,custo:6.0,unit:6.0,minimo:3,minQty:3,forn:''},
  {id:131,nome:'Fita Crepe Automotiva 48mm',name:'Fita Crepe Automotiva 48mm',cat:'masc',unid:'Un',qty:0,custo:8.0,unit:8.0,minimo:3,minQty:3,forn:''},
  {id:132,nome:'Papel de Mascaramento',name:'Papel de Mascaramento',cat:'masc',unid:'Un',qty:0,custo:12.0,unit:12.0,minimo:2,minQty:2,forn:''},
  {id:133,nome:'Plástico de Proteção (rolo)',name:'Plástico de Proteção (rolo)',cat:'masc',unid:'Rolo',qty:0,custo:15.0,unit:15.0,minimo:1,minQty:1,forn:''},
  {id:134,nome:'Fita Fina para Detalhes',name:'Fita Fina para Detalhes',cat:'masc',unid:'Un',qty:0,custo:9.0,unit:9.0,minimo:2,minQty:2,forn:''},
  {id:135,nome:'Tinta Base Sólida (1L)',name:'Tinta Base Sólida (1L)',cat:'pint',unid:'L',qty:0,custo:165.0,unit:165.0,minimo:1,minQty:1,forn:''},
  {id:136,nome:'Tinta Base Metálica (1L)',name:'Tinta Base Metálica (1L)',cat:'pint',unid:'L',qty:0,custo:185.0,unit:185.0,minimo:1,minQty:1,forn:''},
  {id:137,nome:'Tinta Base Perolizada (1L)',name:'Tinta Base Perolizada (1L)',cat:'pint',unid:'L',qty:0,custo:210.0,unit:210.0,minimo:1,minQty:1,forn:''},
  {id:138,nome:'Verniz Urethane PU (1L)',name:'Verniz Urethane PU (1L)',cat:'pint',unid:'L',qty:0,custo:220.0,unit:220.0,minimo:1,minQty:1,forn:''},
  {id:139,nome:'Verniz Alto Sólido HS (1L)',name:'Verniz Alto Sólido HS (1L)',cat:'pint',unid:'L',qty:0,custo:280.0,unit:280.0,minimo:1,minQty:1,forn:''},
  {id:140,nome:'Verniz Acrílico (1L)',name:'Verniz Acrílico (1L)',cat:'pint',unid:'L',qty:0,custo:180.0,unit:180.0,minimo:1,minQty:1,forn:''},
  {id:141,nome:'Thinner / Redutor (1L)',name:'Thinner / Redutor (1L)',cat:'pint',unid:'L',qty:0,custo:35.0,unit:35.0,minimo:2,minQty:2,forn:''},
  {id:142,nome:'Hardener / Catalisador (500ml)',name:'Hardener / Catalisador (500ml)',cat:'pint',unid:'Un',qty:0,custo:65.0,unit:65.0,minimo:1,minQty:1,forn:''},
  {id:143,nome:'Ponte Aderente',name:'Ponte Aderente',cat:'pint',unid:'L',qty:0,custo:55.0,unit:55.0,minimo:1,minQty:1,forn:''},
  {id:144,nome:'Aditivo Anti-silicone',name:'Aditivo Anti-silicone',cat:'pint',unid:'L',qty:0,custo:48.0,unit:48.0,minimo:1,minQty:1,forn:''},
  {id:145,nome:'Diluente de Limpeza (1L)',name:'Diluente de Limpeza (1L)',cat:'pint',unid:'L',qty:0,custo:18.0,unit:18.0,minimo:2,minQty:2,forn:''},
  {id:146,nome:'Composto de Corte',name:'Composto de Corte',cat:'polit',unid:'Un',qty:0,custo:65.0,unit:65.0,minimo:1,minQty:1,forn:''},
  {id:147,nome:'Composto de Refino',name:'Composto de Refino',cat:'polit',unid:'Un',qty:0,custo:68.0,unit:68.0,minimo:1,minQty:1,forn:''},
  {id:148,nome:'Composto de Lustro / Finesse',name:'Composto de Lustro / Finesse',cat:'polit',unid:'Un',qty:0,custo:72.0,unit:72.0,minimo:1,minQty:1,forn:''},
  {id:149,nome:'Polidor Líquido / Cera Líquida',name:'Polidor Líquido / Cera Líquida',cat:'polit',unid:'Un',qty:0,custo:55.0,unit:55.0,minimo:1,minQty:1,forn:''},
  {id:150,nome:'Boina de Corte (lã)',name:'Boina de Corte (lã)',cat:'polit',unid:'Un',qty:0,custo:35.0,unit:35.0,minimo:2,minQty:2,forn:''},
  {id:151,nome:'Boina de Corte (espuma agressa)',name:'Boina de Corte (espuma agressa)',cat:'polit',unid:'Un',qty:0,custo:22.0,unit:22.0,minimo:2,minQty:2,forn:''},
  {id:152,nome:'Boina de Refino (espuma média)',name:'Boina de Refino (espuma média)',cat:'polit',unid:'Un',qty:0,custo:22.0,unit:22.0,minimo:2,minQty:2,forn:''},
  {id:153,nome:'Boina de Polimento (espuma fin)',name:'Boina de Polimento (espuma fin)',cat:'polit',unid:'Un',qty:0,custo:20.0,unit:20.0,minimo:2,minQty:2,forn:''},
  {id:154,nome:'Lixa de Polimento 3000',name:'Lixa de Polimento 3000',cat:'polit',unid:'Un',qty:0,custo:5.5,unit:5.5,minimo:5,minQty:5,forn:''},
  {id:155,nome:'Lixa de Polimento 5000',name:'Lixa de Polimento 5000',cat:'polit',unid:'Un',qty:0,custo:6.0,unit:6.0,minimo:5,minQty:5,forn:''},
  {id:156,nome:'Lixa de Polimento 7000',name:'Lixa de Polimento 7000',cat:'polit',unid:'Un',qty:0,custo:6.5,unit:6.5,minimo:5,minQty:5,forn:''},
  {id:157,nome:'Almofada / Espuma Aplicação',name:'Almofada / Espuma Aplicação',cat:'polit',unid:'Un',qty:0,custo:8.0,unit:8.0,minimo:3,minQty:3,forn:''},
  {id:158,nome:'Descontaminante (ferro/piche)',name:'Descontaminante (ferro/piche)',cat:'limp',unid:'L',qty:0,custo:55.0,unit:55.0,minimo:1,minQty:1,forn:''},
  {id:159,nome:'Clay Bar (barra de argila)',name:'Clay Bar (barra de argila)',cat:'limp',unid:'Un',qty:0,custo:45.0,unit:45.0,minimo:1,minQty:1,forn:''},
  {id:160,nome:'Selante de Pintura',name:'Selante de Pintura',cat:'limp',unid:'L',qty:0,custo:80.0,unit:80.0,minimo:1,minQty:1,forn:''},
  {id:161,nome:'Coating Cerâmico / Nano',name:'Coating Cerâmico / Nano',cat:'limp',unid:'Un',qty:0,custo:180.0,unit:180.0,minimo:1,minQty:1,forn:''},
  {id:162,nome:'Cera Automotiva',name:'Cera Automotiva',cat:'limp',unid:'Un',qty:0,custo:65.0,unit:65.0,minimo:1,minQty:1,forn:''},
  {id:163,nome:'Removedor de Insetos/Alcatrão',name:'Removedor de Insetos/Alcatrão',cat:'limp',unid:'L',qty:0,custo:38.0,unit:38.0,minimo:1,minQty:1,forn:''},
  {id:164,nome:'Luvas de Nitrila (caixa 100)',name:'Luvas de Nitrila (caixa 100)',cat:'outros',unid:'Caixa',qty:0,custo:42.0,unit:42.0,minimo:1,minQty:1,forn:''},
  {id:165,nome:'Papel Toalha (pacote)',name:'Papel Toalha (pacote)',cat:'outros',unid:'Un',qty:0,custo:25.0,unit:25.0,minimo:2,minQty:2,forn:''},
  {id:166,nome:'Flanela de Microfibra',name:'Flanela de Microfibra',cat:'outros',unid:'Un',qty:0,custo:12.0,unit:12.0,minimo:3,minQty:3,forn:''},
  {id:167,nome:'Fita Dupla-face Automotiva',name:'Fita Dupla-face Automotiva',cat:'outros',unid:'Un',qty:0,custo:18.0,unit:18.0,minimo:2,minQty:2,forn:''},
  {id:168,nome:'Espátula de Aplicação',name:'Espátula de Aplicação',cat:'outros',unid:'Un',qty:0,custo:8.0,unit:8.0,minimo:2,minQty:2,forn:''},
  {id:169,nome:'Disco de Corte 4.5"',name:'Disco de Corte 4.5"',cat:'outros',unid:'Un',qty:0,custo:8.0,unit:8.0,minimo:5,minQty:5,forn:''},
  {id:170,nome:'Disco de Desbaste 4.5"',name:'Disco de Desbaste 4.5"',cat:'outros',unid:'Un',qty:0,custo:12.0,unit:12.0,minimo:3,minQty:3,forn:''}
]);
