import { formatBRL } from '../../core/money.js';

function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!=null)n.textContent=text;return n;}
function field(label,type='text'){const wrap=el('label','field');wrap.append(el('span','field-label',label));const input=el('input');input.type=type;wrap.append(input);return {wrap,input};}
function selectField(label,options=[]){const wrap=el('label','field');wrap.append(el('span','field-label',label));const select=el('select');for(const [value,name] of options){const o=el('option','',name);o.value=value;select.append(o);}wrap.append(select);return {wrap,select};}
function isoMonth(d=new Date()){return {year:d.getFullYear(),month:d.getMonth()};}
function monthLabel(year,month){return new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(new Date(year,month,1)).replace(/^./,c=>c.toUpperCase());}
function paidText(row){return row.paid===true||String(row.paid).toLowerCase()==='pago'?'Pago':'Pendente';}

export function renderFinanceiroView(root,{service,onChanged=()=>{}}){
  root.replaceChildren();root.className='finance-module';let period=isoMonth(),editingId=null,flowDays=30;
  const title=el('section','card');title.append(el('h1','','Financeiro'),el('p','','Receitas, despesas, transferências e fluxo de caixa. Contas vinculadas compartilham o mesmo lançamento para impedir dupla contagem.'));
  const periodCard=el('section','card');const periodRow=el('div','module-toolbar');const prev=el('button','btn','‹');const label=el('strong','toolbar-title');const next=el('button','btn','›');prev.type=next.type='button';periodRow.append(prev,label,next);periodCard.append(periodRow);
  const metrics=el('div','metrics');periodCard.append(metrics);

  const entry=el('section','card');entry.append(el('h2','','Novo lançamento / edição'));
  const form=el('form','form-grid');const type=selectField('Tipo',[['rec','Receita'],['dep','Despesa']]);const desc=field('Descrição');const val=field('Valor','text');val.input.inputMode='decimal';const date=field('Data','date');const cat=field('Categoria');const paid=selectField('Situação',[['Pago','Pago'],['Não pago','Pendente']]);
  const save=el('button','btn btn-primary','Salvar');save.type='submit';const cancel=el('button','btn','Cancelar edição');cancel.type='button';cancel.hidden=true;form.append(type.wrap,desc.wrap,val.wrap,date.wrap,cat.wrap,paid.wrap,save,cancel);entry.append(form);
  const feedback=el('p','status-line');entry.append(feedback);
  const sync=el('button','btn','Sincronizar OS entregues');sync.type='button';title.append(sync);
  sync.addEventListener('click',async()=>{sync.disabled=true;try{const result=await service.syncDeliveredWorkOrders();feedback.textContent=`${result.added} receita(s) criada(s). ${result.ordersUpdated} OS sincronizada(s). As novas receitas ficam pendentes de pagamento.`;await refresh();onChanged();}catch(error){feedback.textContent=error.message;}finally{sync.disabled=false;}});

  const transfer=el('section','card');transfer.append(el('h2','','Transferência entre saldos'));const tf=el('form','form-grid');const from=selectField('Origem',[['sicoob','Sicoob'],['dinheiro','Dinheiro/Caixa'],['pix','PIX/Outros']]);const to=selectField('Destino',[['dinheiro','Dinheiro/Caixa'],['sicoob','Sicoob'],['pix','PIX/Outros']]);const tval=field('Valor','text');tval.input.inputMode='decimal';const tdate=field('Data','date');const tdesc=field('Descrição');tdesc.input.value='Transferência interna';const tsave=el('button','btn','Transferir');tsave.type='submit';tf.append(from.wrap,to.wrap,tval.wrap,tdate.wrap,tdesc.wrap,tsave);transfer.append(tf);
  const balances=el('div','metrics');transfer.append(balances);

  const filters=el('section','card');filters.append(el('h2','','Lançamentos'));const filterRow=el('div','module-toolbar');const search=el('input','search-input');search.placeholder='Buscar descrição ou categoria';const fType=el('select');[['','Todos'],['rec','Receitas'],['dep','Despesas'],['transfer','Transferências']].forEach(([v,n])=>{const o=el('option','',n);o.value=v;fType.append(o);});filterRow.append(search,fType);filters.append(filterRow);const list=el('div','stack-list');filters.append(list);

  const flow=el('section','card');flow.append(el('h2','','Fluxo projetado'));const flowBtns=el('div','actions');for(const days of [30,60,90]){const b=el('button','btn',`${days} dias`);b.type='button';b.addEventListener('click',()=>{flowDays=days;refreshFlow();});flowBtns.append(b);}const flowSummary=el('div','metrics');const flowList=el('div','stack-list');flow.append(flowBtns,flowSummary,flowList);
  const body=el('div','finance-layout');const main=el('div','finance-main');const middle=el('div','finance-middle');const side=el('aside','finance-side');main.append(periodCard,filters);middle.append(entry,transfer);side.append(flow);body.append(main,middle,side);root.append(title,body);

  function reset(){editingId=null;form.reset();type.select.value='rec';paid.select.value='Pago';date.input.value=new Date().toISOString().slice(0,10);cancel.hidden=true;save.textContent='Salvar';}
  async function refreshBalances(){const bank=await service.bankState();balances.replaceChildren();for(const [key,name] of [['sicoob','Sicoob'],['dinheiro','Dinheiro/Caixa'],['pix','PIX/Outros']]){const card=el('article','metric');card.append(el('span','metric-label',name),el('strong','metric-value',formatBRL(bank.saldos[key]||0)));const edit=el('button','link-btn','Ajustar saldo');edit.type='button';edit.addEventListener('click',async()=>{const v=window.prompt(`Saldo atual — ${name}:`,String(bank.saldos[key]||0).replace('.',','));if(v===null)return;await service.setBankBalance(key,v);await refreshBalances();await refreshFlow();onChanged();});card.append(edit);balances.append(card);}}
  async function refreshFlow(){const data=await service.cashFlow({from:new Date().toISOString().slice(0,10),days:flowDays});flowSummary.replaceChildren();[['Saldo inicial',data.openingBalance],['Entradas previstas',data.totalIn],['Saídas previstas',data.totalOut],['Saldo projetado',data.closingBalance]].forEach(([n,v])=>{const c=el('article','metric');c.append(el('span','metric-label',n),el('strong','metric-value',formatBRL(v)));flowSummary.append(c);});flowList.replaceChildren();if(!data.events.length)flowList.append(el('p','empty','Nenhum evento projetado no período.'));for(const e of data.events){const row=el('article','list-row');const info=el('div','list-main');info.append(el('strong','',e.desc),el('span','muted',`${e.date} · ${e.source==='accounts'?'Contas':'Agenda'}`));const side=el('div','list-side');side.append(el('strong',e.type==='rec'?'positive':'negative',`${e.type==='rec'?'+':'−'} ${formatBRL(e.val)}`),el('span','muted',`Saldo: ${formatBRL(e.balance)}`));row.append(info,side);flowList.append(row);}}
  async function refresh(){label.textContent=monthLabel(period.year,period.month);const [sum,rows]=await Promise.all([service.summary(period.year,period.month),service.list({year:period.year,month:period.month,query:search.value,type:fType.value})]);metrics.replaceChildren();[['Receitas',sum.totalReceipts],['Despesas',sum.totalExpenses],['Resultado',sum.result],['Margem',`${sum.margin.toFixed(1)}%`]].forEach(([n,v])=>{const c=el('article','metric');c.dataset.indicator=n;c.append(el('span','metric-label',n),el('strong','metric-value',typeof v==='number'?formatBRL(v):v));metrics.append(c);});list.replaceChildren();if(!rows.length)list.append(el('p','empty','Nenhum lançamento neste período.'));for(const row of rows){const item=el('article','list-row');const main=el('div','list-main');main.append(el('strong','',row.desc),el('span','muted',`${row.date} · ${row.cat} · ${row.type==='rec'?'Receita':row.type==='transfer'?'Transferência':'Despesa'} · ${paidText(row)}`));if(row.contaId)main.append(el('span','tag',`Conta ${row.contaId}`));const side=el('div','list-side');const amountEl=el('strong',row.type==='rec'?'positive':row.type==='dep'?'negative':'',formatBRL(row.val));const actions=el('div','row-actions');if(row.type!=='transfer'){const edit=el('button','link-btn','Editar');edit.type='button';edit.addEventListener('click',()=>{editingId=row.id;type.select.value=row.type;desc.input.value=row.desc;val.input.value=String(row.val).replace('.',',');date.input.value=row.date;cat.input.value=row.cat;paid.select.value=paidText(row)==='Pago'?'Pago':'Não pago';cancel.hidden=false;save.textContent='Atualizar';entry.scrollIntoView({behavior:'smooth',block:'start'});});const toggle=el('button','link-btn',paidText(row)==='Pago'?'Desfazer':'Pagar');toggle.type='button';toggle.addEventListener('click',async()=>{await service.setPaid(row.id,paidText(row)!=='Pago');await refresh();onChanged();});actions.append(edit,toggle);}const del=el('button','link-btn danger',row.type==='transfer'?'Estornar':'Excluir');del.type='button';del.addEventListener('click',async()=>{if(!window.confirm(row.type==='transfer'?'Estornar esta transferência?':'Excluir este lançamento e a Conta vinculada, quando houver?'))return;await service.remove(row.id);await refresh();await refreshBalances();await refreshFlow();onChanged();});actions.append(del);side.append(amountEl,actions);item.append(main,side);list.append(item);}await refreshBalances();await refreshFlow();}

  form.addEventListener('submit',async e=>{e.preventDefault();try{const payload={type:type.select.value,desc:desc.input.value,val:val.input.value,date:date.input.value,cat:cat.input.value,paid:paid.select.value};if(editingId)await service.update(editingId,payload);else await service.create(payload);feedback.textContent=editingId?'Lançamento atualizado.':'Lançamento salvo.';reset();await refresh();onChanged();}catch(err){feedback.textContent=err.message;}});
  cancel.addEventListener('click',reset);
  tf.addEventListener('submit',async e=>{e.preventDefault();try{await service.transfer({fromAccount:from.select.value,toAccount:to.select.value,val:tval.input.value,date:tdate.input.value||new Date().toISOString().slice(0,10),desc:tdesc.input.value||'Transferência interna'});tf.reset();tdesc.input.value='Transferência interna';await refresh();onChanged();}catch(err){feedback.textContent=err.message;}});
  prev.addEventListener('click',()=>{period.month-=1;if(period.month<0){period.month=11;period.year-=1;}refresh();});next.addEventListener('click',()=>{period.month+=1;if(period.month>11){period.month=0;period.year+=1;}refresh();});search.addEventListener('input',refresh);fType.addEventListener('change',refresh);
  reset();tdate.input.value=new Date().toISOString().slice(0,10);refresh();return {refresh};
}
